"""Lambert's problem: verification by independent propagation, closed forms, and failures.

The load-bearing test in this file is
:func:`test_lambert_velocity_propagates_onto_the_target_position`. Everything else supports
it. ``rpo_core.propagate.propagate_two_body`` is validated separately (energy and angular
momentum conserved to better than 1e-10 relative over ten orbits, monotone convergence under
tolerance tightening), and it shares no code with ``rpo_core.lambert``: it integrates the
equation of motion where Lambert solves a boundary value problem in closed form plus one
scalar root. Feeding Lambert's departure velocity into that integrator and asking where it
ends up is therefore an external oracle, not a restatement of the solver's own arithmetic.

Numbers quoted in tolerance comments were measured on this machine before the bound was
chosen; the headroom is stated in each case.
"""

import math

import numpy as np
import pytest
from rpo_core.constants import (
    MU_EARTH_M3_S2,
    R_EARTH_EQUATORIAL_M,
    orbital_period_s,
)
from rpo_core.exceptions import DegenerateGeometryError, InfeasibleTransferError
from rpo_core.lambert import (
    LambertConvergenceError,
    minimum_multirev_time_s,
    solve_lambert,
    stumpff_c,
    stumpff_s,
    transfer_angle_rad,
)
from rpo_core.propagate import (
    propagate_two_body,
    specific_angular_momentum,
    specific_energy_j_kg,
)

MU = MU_EARTH_M3_S2
A_LEO_M = R_EARTH_EQUATORIAL_M + 420.0e3
PERIOD_S = orbital_period_s(A_LEO_M)
V_CIRCULAR = math.sqrt(MU / A_LEO_M)

R1_LEO = np.array([A_LEO_M, 0.0, 0.0])
R2_LEO_QUARTER = np.array([0.0, A_LEO_M, 0.0])


def _state_at_periapsis(eccentricity: float) -> tuple[np.ndarray, float]:
    """Return an inertial state at periapsis radius ``A_LEO_M`` and its orbital period."""
    speed = math.sqrt(MU * (1.0 + eccentricity) / A_LEO_M)
    state = np.array([A_LEO_M, 0.0, 0.0, 0.0, speed, 0.0])
    return state, orbital_period_s(A_LEO_M / (1.0 - eccentricity))


def _endpoints(eccentricity: float, period_fraction: float, **kwargs: float) -> tuple:
    """Propagate a reference arc and return ``(r1, r2, tof, truth_state_at_r2)``.

    The reference arc is generated by the integrator, so ``(r1, r2, tof)`` is guaranteed to
    be a triple that a real two-body trajectory actually connects. Handing Lambert a
    geometrically arbitrary triple would test far less: the solver would still return an
    answer, but there would be no independently known velocity to compare against.
    """
    state, period = _state_at_periapsis(eccentricity)
    tof = period_fraction * period
    arc = propagate_two_body(state, np.array([0.0, tof]), MU, **kwargs)
    return arc[0][:3], arc[-1][:3], tof, arc[-1]


# Spread of transfer angles: 28.8 deg and 38.6 deg are well below 180; 216, 253, 290 and 306
# are well above; 90, 71.7, 106.9 and 122.3 straddle the right angle. Eccentricity runs from
# circular to 0.75 so the arcs are not all near-circular, where a sign error in the geometry
# constant A would be hidden by r1 == r2.
_PROPAGATION_CASES = [
    (ecc, frac) for ecc in (0.0, 0.15, 0.45, 0.75) for frac in (0.08, 0.25, 0.40, 0.60, 0.85)
]


@pytest.mark.integration
@pytest.mark.parametrize(("eccentricity", "period_fraction"), _PROPAGATION_CASES)
def test_lambert_velocity_propagates_onto_the_target_position(eccentricity, period_fraction):
    """The oracle test: fly the solved departure velocity and check where it lands.

    Bound set from measurement. Across these twenty cases the worst position residual is
    7.09e-4 m -- 2.40e-11 of the arrival radius -- at the package-default integrator
    tolerance of 1e-12. The assertion is made relative to the arrival radius because the
    cases span radii from 6.8e6 m to 4.8e7 m, and 1e-9 leaves roughly forty times headroom
    over the worst measured value while still being four decades tighter than any error a
    wrong branch, a wrong quadrant, or a dropped term could produce.
    """
    r1, r2, tof, _ = _endpoints(eccentricity, period_fraction)
    v1, _ = solve_lambert(r1, r2, tof, MU)

    arrival = propagate_two_body(np.concatenate([r1, v1]), np.array([0.0, tof]), MU)[-1]
    residual_m = float(np.linalg.norm(arrival[:3] - r2))
    relative = residual_m / float(np.linalg.norm(r2))
    assert relative < 1e-9, (
        f"propagating the Lambert v1 for {tof:.3f} s missed r2 by {residual_m:.6e} m "
        f"({relative:.3e} relative)"
    )


@pytest.mark.integration
@pytest.mark.parametrize(("eccentricity", "period_fraction"), _PROPAGATION_CASES)
def test_lambert_arrival_velocity_matches_the_propagated_arrival_velocity(
    eccentricity, period_fraction
):
    """``v2`` must equal the velocity the integrator reports on arrival, not just ``v1``.

    Without this, a solver that got ``v1`` right and ``v2`` from a mistyped Lagrange
    coefficient would pass every other test in the file.
    """
    r1, r2, tof, truth = _endpoints(eccentricity, period_fraction)
    _, v2 = solve_lambert(r1, r2, tof, MU)
    error = float(np.linalg.norm(v2 - truth[3:]))
    speed = float(np.linalg.norm(truth[3:]))
    assert error / speed < 1e-9, f"v2 off by {error:.3e} m/s on a {speed:.3f} m/s arrival"


@pytest.mark.integration
def test_propagate_back_residual_shrinks_as_the_integrator_tightens():
    """Show the residual above is the *integrator's* error, not Lambert's.

    A single threshold cannot distinguish "Lambert is accurate" from "Lambert is wrong by
    less than a loose bound". If the miss distance is dominated by integration error it must
    fall when the integrator tolerance falls, and Lambert's own contribution is whatever is
    left at the tightest setting. Measured: 2.58e-2, 3.85e-3, 7.49e-4, 1.13e-4, 8.73e-6 m at
    rtol = 1e-9 ... 1e-13, i.e. a clean three-and-a-half decade descent tracking the
    integrator, which puts Lambert's own error below 1e-5 m on a 1.8e7 m arc.
    """
    residuals = []
    for tol in (1e-9, 1e-10, 1e-11, 1e-12, 1e-13):
        r1, r2, tof, _ = _endpoints(0.45, 0.60, rtol=tol, atol=tol)
        v1, _ = solve_lambert(r1, r2, tof, MU)
        arrival = propagate_two_body(
            np.concatenate([r1, v1]), np.array([0.0, tof]), MU, rtol=tol, atol=tol
        )[-1]
        residuals.append(float(np.linalg.norm(arrival[:3] - r2)))

    assert all(residuals[i] > residuals[i + 1] for i in range(len(residuals) - 1)), (
        f"miss distance did not shrink monotonically with integrator tolerance: {residuals}"
    )
    assert residuals[-1] < 1e-4, f"residual floor {residuals[-1]:.3e} m is above 0.1 mm"


# --------------------------------------------------------------------------------------
# Closed-form and published cases
# --------------------------------------------------------------------------------------


@pytest.mark.unit
def test_quarter_orbit_of_a_circular_orbit_returns_the_circular_speed():
    """Analytic limiting case: the arc *is* the circular orbit, so both speeds are v_circ.

    Measured error 9.1e-13 m/s on a 7660 m/s speed; the 1e-9 bound is three decades of
    headroom.
    """
    v1, v2 = solve_lambert(R1_LEO, R2_LEO_QUARTER, 0.25 * PERIOD_S, MU)
    assert float(np.linalg.norm(v1)) == pytest.approx(V_CIRCULAR, abs=1e-9)
    assert float(np.linalg.norm(v2)) == pytest.approx(V_CIRCULAR, abs=1e-9)
    # The velocity must also point the right way: purely along-track at the start.
    np.testing.assert_allclose(v1, [0.0, V_CIRCULAR, 0.0], atol=1e-6)


@pytest.mark.unit
def test_hohmann_delta_v_is_recovered_as_the_transfer_angle_approaches_180_degrees():
    r"""The 180-degree transfer is the Hohmann transfer, approached as a limit.

    A Hohmann transfer between coplanar circular orbits is a 180-degree Lambert problem with
    the time of flight equal to half the transfer-ellipse period -- which is exactly the
    degenerate case this module refuses to solve, because at :math:`\Delta\theta = \pi` the
    two position vectors are collinear and the transfer plane is undefined. So it is
    approached from below: 178, 179, 179.9 and 179.99 degrees, asserting that the error
    against the closed-form Hohmann delta-v *shrinks monotonically*, which no single
    hand-picked angle could demonstrate.

    Measured total delta-v error: 3.80, 9.49e-1, 9.48e-3, 5.48e-5 m/s against a 3406.264 m/s
    Hohmann total. The 1e-4 m/s bound at 179.99 degrees is about a factor of two of headroom
    -- deliberately tight, because past this point the limit stops improving (see
    ``test_the_transfer_plane_becomes_ill_conditioned_near_180_degrees``) and a looser bound
    would hide that.
    """
    r_inner = R_EARTH_EQUATORIAL_M + 400.0e3
    r_outer = R_EARTH_EQUATORIAL_M + 20000.0e3
    a_transfer = 0.5 * (r_inner + r_outer)
    tof = math.pi * math.sqrt(a_transfer**3 / MU)

    v_circ_inner = math.sqrt(MU / r_inner)
    v_circ_outer = math.sqrt(MU / r_outer)
    dv1_closed = v_circ_inner * (math.sqrt(2.0 * r_outer / (r_inner + r_outer)) - 1.0)
    dv2_closed = v_circ_outer * (1.0 - math.sqrt(2.0 * r_inner / (r_inner + r_outer)))
    total_closed = dv1_closed + dv2_closed

    errors = []
    for degrees in (178.0, 179.0, 179.9, 179.99):
        angle = math.radians(degrees)
        r1 = np.array([r_inner, 0.0, 0.0])
        r2 = r_outer * np.array([math.cos(angle), math.sin(angle), 0.0])
        v1, v2 = solve_lambert(r1, r2, tof, MU)

        departure = float(np.linalg.norm(v1 - np.array([0.0, v_circ_inner, 0.0])))
        arrival_circular = v_circ_outer * np.cross([0.0, 0.0, 1.0], r2 / np.linalg.norm(r2))
        arrival = float(np.linalg.norm(arrival_circular - v2))
        errors.append(abs(departure + arrival - total_closed))

    assert all(errors[i] > errors[i + 1] for i in range(len(errors) - 1)), (
        f"Hohmann agreement did not improve monotonically towards 180 deg: {errors}"
    )
    assert errors[-1] < 1e-4, (
        f"at 179.99 deg the total delta-v is off the closed-form Hohmann value by "
        f"{errors[-1]:.3e} m/s (total {total_closed:.6f} m/s)"
    )


# Curtis, "Orbital Mechanics for Engineering Students", 3rd ed., Example 5.2:
# r1 = [5000, 10000, 2100] km, r2 = [-14600, 2500, 7000] km, prograde, dt = 3600 s.
#
# UNVERIFIED CITATION — do not repeat this reference publicly until someone checks the book.
#
# The expected velocities below are transcribed from recollection of the printed example,
# not from a copy of the book. They are retained as a REGRESSION PIN, not as evidence of
# agreement with published literature, and the test name says so.
#
# One earlier justification for keeping them was wrong and is recorded here so it is not
# repeated: "this module's independent implementation reproduces them" is NOT independent
# corroboration. The recalled numbers and the implementation come from the same source, so
# their agreement is correlated error, not confirmation.
#
# What IS independently verified is the physics, by
# `test_curtis_case_is_consistent_with_the_validated_integrator`: propagating (r1, v1)
# through `propagate_two_body` for the requested time of flight arrives at r2 with a
# measured position error of 1.17e-5 m. That check knows nothing about these six numbers
# and is the reason to trust the solver.
#
# Backlog item X6 tracks verifying the citation against a physical copy. Until then, treat
# the geometry and time of flight as a fixture and the velocities as a pinned regression.
_CURTIS_R1_M = np.array([5000.0, 10000.0, 2100.0]) * 1.0e3
_CURTIS_R2_M = np.array([-14600.0, 2500.0, 7000.0]) * 1.0e3
_CURTIS_TOF_S = 3600.0
_CURTIS_V1_M_S = np.array([-5.9925, 1.9254, 3.2456]) * 1.0e3
_CURTIS_V2_M_S = np.array([-3.3125, -4.1966, -0.38529]) * 1.0e3


@pytest.mark.unit
def test_curtis_case_matches_its_pinned_regression_values():
    """Reproduce a published textbook case; see the honesty note above the constants.

    The tolerance is set by the *book's* precision, not this solver's: the expected values
    carry five significant figures, so 1e-4 relative is the tightest assertion the published
    numbers can support.
    """
    v1, v2 = solve_lambert(_CURTIS_R1_M, _CURTIS_R2_M, _CURTIS_TOF_S, MU, prograde=True)
    np.testing.assert_allclose(v1, _CURTIS_V1_M_S, rtol=1e-4)
    np.testing.assert_allclose(v2, _CURTIS_V2_M_S, rtol=1e-4)


@pytest.mark.integration
def test_curtis_case_is_consistent_with_the_validated_integrator():
    """Corroborate the textbook case against the propagator, which knows no book values."""
    v1, v2 = solve_lambert(_CURTIS_R1_M, _CURTIS_R2_M, _CURTIS_TOF_S, MU)
    arrival = propagate_two_body(
        np.concatenate([_CURTIS_R1_M, v1]), np.array([0.0, _CURTIS_TOF_S]), MU
    )[-1]
    assert float(np.linalg.norm(arrival[:3] - _CURTIS_R2_M)) < 1e-3
    assert float(np.linalg.norm(arrival[3:] - v2)) < 1e-6


# --------------------------------------------------------------------------------------
# Conservation laws and symmetries
# --------------------------------------------------------------------------------------


@pytest.mark.unit
@pytest.mark.parametrize(("eccentricity", "period_fraction"), _PROPAGATION_CASES)
def test_energy_and_angular_momentum_agree_at_the_two_endpoints(eccentricity, period_fraction):
    """The returned pair must describe one conic, not two unrelated velocities.

    Measured worst relative disagreement 2.9e-15 in energy and 1.3e-16 in angular momentum;
    1e-12 is three decades of headroom and still far tighter than any inconsistency a real
    error would produce.
    """
    r1, r2, tof, _ = _endpoints(eccentricity, period_fraction)
    v1, v2 = solve_lambert(r1, r2, tof, MU)

    energy_1 = specific_energy_j_kg(np.concatenate([r1, v1]), MU)
    energy_2 = specific_energy_j_kg(np.concatenate([r2, v2]), MU)
    assert abs(energy_1 - energy_2) / abs(energy_1) < 1e-12

    h1 = specific_angular_momentum(np.concatenate([r1, v1]))
    h2 = specific_angular_momentum(np.concatenate([r2, v2]))
    assert float(np.linalg.norm(h1 - h2)) / float(np.linalg.norm(h1)) < 1e-12


@pytest.mark.unit
def test_swapping_the_endpoints_gives_the_time_reversed_solution():
    """Time reversal: solve backwards and the velocities negate exactly.

    The direction flag must flip as well, and that is the point of the test. Negating both
    velocities reverses the specific angular momentum, so the time-reversed arc has the
    opposite sign of ``h_z`` -- a prograde transfer run backwards is a retrograde one. A
    solver that ignored ``prograde`` entirely would fail this; so would one that flipped it
    in the wrong place.
    """
    r1, r2, tof, _ = _endpoints(0.30, 0.37)
    v1, v2 = solve_lambert(r1, r2, tof, MU, prograde=True)
    w1, w2 = solve_lambert(r2, r1, tof, MU, prograde=False)

    np.testing.assert_allclose(w1, -v2, rtol=1e-12, atol=1e-9)
    np.testing.assert_allclose(w2, -v1, rtol=1e-12, atol=1e-9)


@pytest.mark.unit
def test_reversing_without_flipping_the_direction_gives_a_different_arc():
    """Complement to the test above: the direction flip is load-bearing, not decorative."""
    r1, r2, tof, _ = _endpoints(0.30, 0.37)
    _, v2 = solve_lambert(r1, r2, tof, MU, prograde=True)
    w1, _ = solve_lambert(r2, r1, tof, MU, prograde=True)
    assert float(np.linalg.norm(w1 - (-v2))) > 1.0e3, (
        "keeping prograde=True on the reversed problem produced the time-reversed answer, "
        "which means the direction convention is not being applied"
    )


# --------------------------------------------------------------------------------------
# Direction of motion
# --------------------------------------------------------------------------------------


@pytest.mark.unit
def test_prograde_and_retrograde_sweep_complementary_angles():
    angle = transfer_angle_rad(R1_LEO, R2_LEO_QUARTER, prograde=True)
    assert math.degrees(angle) == pytest.approx(90.0)
    angle = transfer_angle_rad(R1_LEO, R2_LEO_QUARTER, prograde=False)
    assert math.degrees(angle) == pytest.approx(270.0)


@pytest.mark.unit
def test_transfer_angle_exceeds_180_when_the_short_way_runs_against_the_direction():
    """A target at -80 deg is 280 deg away going prograde, and 80 deg going retrograde."""
    angle = math.radians(-80.0)
    r2 = A_LEO_M * np.array([math.cos(angle), math.sin(angle), 0.0])
    assert math.degrees(transfer_angle_rad(R1_LEO, r2, prograde=True)) == pytest.approx(280.0)
    assert math.degrees(transfer_angle_rad(R1_LEO, r2, prograde=False)) == pytest.approx(80.0)


@pytest.mark.integration
def test_prograde_and_retrograde_are_genuinely_different_transfers():
    """Complement test: prove ``prograde`` changes the answer, and both answers are valid.

    A flag that is read but never used would leave every other test in this file passing.
    Both solutions are checked against the propagator, so this is not merely "the numbers
    differ" -- they are two distinct correct arcs, in planes with opposite ``h_z``.
    """
    r1 = np.array([A_LEO_M, 0.0, 0.0])
    r2 = np.array([0.0, 0.9 * A_LEO_M, 0.3 * A_LEO_M])
    tof = 0.30 * PERIOD_S

    v_pro, _ = solve_lambert(r1, r2, tof, MU, prograde=True)
    v_retro, _ = solve_lambert(r1, r2, tof, MU, prograde=False)

    separation = float(np.linalg.norm(v_pro - v_retro))
    assert separation > 1.0e3, f"prograde and retrograde differ by only {separation:.3e} m/s"

    h_pro = float(np.cross(r1, v_pro)[2])
    h_retro = float(np.cross(r1, v_retro)[2])
    assert h_pro > 0.0 and h_retro < 0.0, (
        f"direction convention violated: h_z is {h_pro:.3e} prograde, {h_retro:.3e} retrograde"
    )

    for velocity in (v_pro, v_retro):
        arrival = propagate_two_body(np.concatenate([r1, velocity]), np.array([0.0, tof]), MU)[-1]
        assert float(np.linalg.norm(arrival[:3] - r2)) / float(np.linalg.norm(r2)) < 1e-9


# --------------------------------------------------------------------------------------
# Stumpff functions
# --------------------------------------------------------------------------------------


@pytest.mark.unit
@pytest.mark.parametrize("z", [-40.0, -12.0, -1.5, -1.0001, 1.0001, 2.5, 20.0, 39.0, 150.0])
def test_stumpff_series_and_closed_forms_agree_across_the_switchover(z):
    """Two independent algorithms for the same function must meet at the threshold.

    Outside ``|z| <= 1`` the module uses the elementary closed form; inside it uses the power
    series. Evaluating the closed form here and comparing catches a wrong factorial offset or
    a wrong branch in either. Measured agreement is at or below 2.3e-16 relative.
    """
    if z > 0.0:
        root = math.sqrt(z)
        expected_c = (1.0 - math.cos(root)) / z
        expected_s = (root - math.sin(root)) / root**3
    else:
        root = math.sqrt(-z)
        expected_c = (math.cosh(root) - 1.0) / (-z)
        expected_s = (math.sinh(root) - root) / root**3
    assert stumpff_c(z) == pytest.approx(expected_c, rel=1e-14)
    assert stumpff_s(z) == pytest.approx(expected_s, rel=1e-14)


@pytest.mark.unit
def test_stumpff_functions_take_their_parabolic_values_at_zero():
    """``C(0) = 1/2`` and ``S(0) = 1/6``: the leading terms of the defining series."""
    assert stumpff_c(0.0) == pytest.approx(0.5, rel=1e-15)
    assert stumpff_s(0.0) == pytest.approx(1.0 / 6.0, rel=1e-15)


@pytest.mark.unit
def test_stumpff_functions_at_the_one_revolution_singularity():
    """At ``z = 4*pi**2`` (one full revolution in eccentric anomaly) ``C`` vanishes.

    This is the analytic reason ``dt(z) -> infinity`` at the ends of every multi-revolution
    interval, so it is worth pinning independently of the solver that relies on it.
    """
    z = 4.0 * math.pi**2
    assert abs(stumpff_c(z)) < 1e-15
    assert stumpff_s(z) == pytest.approx(1.0 / (4.0 * math.pi**2), rel=1e-12)


@pytest.mark.unit
def test_stumpff_functions_are_continuous_across_the_series_threshold():
    """No visible seam where the implementation switches algorithm."""
    for side in (-1.0, 1.0):
        below = stumpff_c(side * (1.0 - 1e-12))
        above = stumpff_c(side * (1.0 + 1e-12))
        assert below == pytest.approx(above, rel=1e-14)
        assert stumpff_s(side * (1.0 - 1e-12)) == pytest.approx(
            stumpff_s(side * (1.0 + 1e-12)), rel=1e-14
        )


# --------------------------------------------------------------------------------------
# Conic type
# --------------------------------------------------------------------------------------


@pytest.mark.unit
def test_short_times_of_flight_give_hyperbolic_arcs_and_long_ones_elliptic():
    """The formulation is meant to cross conic types without branching; check that it does.

    A quarter-turn in a tenth of an orbital period cannot be done on a bound orbit, so the
    specific energy must come out positive. This is also a complement test for the universal
    variable: a solver that silently clamped ``z >= 0`` would return an elliptic arc here and
    quietly miss the target.
    """
    energies = []
    for fraction in (0.05, 0.10, 0.25, 0.50, 0.90):
        v1, _ = solve_lambert(R1_LEO, R2_LEO_QUARTER, fraction * PERIOD_S, MU)
        energies.append(specific_energy_j_kg(np.concatenate([R1_LEO, v1]), MU))
    assert energies[0] > 0.0 and energies[1] > 0.0, f"short arcs are not hyperbolic: {energies}"
    assert all(e < 0.0 for e in energies[2:]), f"long arcs are not elliptic: {energies}"


# --------------------------------------------------------------------------------------
# Multiple revolutions
# --------------------------------------------------------------------------------------

_MULTIREV_R1 = np.array([A_LEO_M, 0.0, 0.0])
_MULTIREV_R2 = np.array([0.0, 1.4 * A_LEO_M, 0.2 * A_LEO_M])


@pytest.mark.integration
@pytest.mark.parametrize("revolutions", [1, 2, 3])
@pytest.mark.parametrize("branch", ["low", "high"])
@pytest.mark.parametrize("time_factor", [1.05, 1.5, 2.5])
def test_multi_revolution_solutions_also_propagate_onto_the_target(
    revolutions, branch, time_factor
):
    """Both multi-revolution branches face the same oracle as the direct transfer."""
    tof = time_factor * minimum_multirev_time_s(
        _MULTIREV_R1, _MULTIREV_R2, MU, revolutions=revolutions
    )
    v1, _ = solve_lambert(
        _MULTIREV_R1, _MULTIREV_R2, tof, MU, revolutions=revolutions, branch=branch
    )
    arrival = propagate_two_body(
        np.concatenate([_MULTIREV_R1, v1]), np.array([0.0, tof]), MU, rtol=1e-13, atol=1e-13
    )[-1]
    relative = float(np.linalg.norm(arrival[:3] - _MULTIREV_R2)) / float(
        np.linalg.norm(_MULTIREV_R2)
    )
    assert relative < 1e-9, f"{branch} {revolutions}-rev arc missed by {relative:.3e} relative"


@pytest.mark.unit
@pytest.mark.parametrize("revolutions", [1, 2, 3])
def test_the_multi_revolution_arc_really_completes_that_many_revolutions(revolutions):
    """Check the *count*, not just that some arc reaches the target.

    Arriving at the right place at the right time is necessary but not sufficient: the whole
    point of ``revolutions=N`` is that the vehicle goes round N times on the way. The transfer
    orbit's own period is known in closed form from the returned velocity, so the number of
    periods elapsed must fall between N and N+1. This is what distinguishes the requested
    branch of a genuinely multi-valued problem from any other arc that happens to fit.
    """
    tof = 1.5 * minimum_multirev_time_s(_MULTIREV_R1, _MULTIREV_R2, MU, revolutions=revolutions)
    v1, _ = solve_lambert(_MULTIREV_R1, _MULTIREV_R2, tof, MU, revolutions=revolutions)

    energy = specific_energy_j_kg(np.concatenate([_MULTIREV_R1, v1]), MU)
    semi_major_axis = -MU / (2.0 * energy)
    laps = tof / orbital_period_s(semi_major_axis, MU)
    assert revolutions <= laps <= revolutions + 1, (
        f"asked for {revolutions} revolutions but the arc covers {laps:.4f} transfer periods"
    )


@pytest.mark.unit
def test_the_two_multi_revolution_branches_are_different_solutions():
    """Complement test: ``branch`` must select, not decorate.

    Both branches solve the same boundary value problem, so a solver that ignored ``branch``
    would still pass the propagation test above for both values. They are distinguished here
    by semi-major axis: the low-``z`` branch is the larger, slower-sweeping ellipse. Measured
    for this geometry at 1.3x the minimum time: a = 9.59e6 m against 7.63e6 m, and the
    departure velocities differ by 5.29e3 m/s.
    """
    tof = 1.3 * minimum_multirev_time_s(_MULTIREV_R1, _MULTIREV_R2, MU, revolutions=1)
    v_low, _ = solve_lambert(_MULTIREV_R1, _MULTIREV_R2, tof, MU, revolutions=1, branch="low")
    v_high, _ = solve_lambert(_MULTIREV_R1, _MULTIREV_R2, tof, MU, revolutions=1, branch="high")

    assert float(np.linalg.norm(v_low - v_high)) > 1.0e3

    a_low = -MU / (2.0 * specific_energy_j_kg(np.concatenate([_MULTIREV_R1, v_low]), MU))
    a_high = -MU / (2.0 * specific_energy_j_kg(np.concatenate([_MULTIREV_R1, v_high]), MU))
    assert a_low > a_high, (
        f"the low-z branch should be the larger ellipse: a_low={a_low:.4e} m, a_high={a_high:.4e} m"
    )


@pytest.mark.unit
def test_multi_revolution_solutions_differ_from_the_direct_transfer():
    """The same time of flight admits a direct arc too; it must not be what N>=1 returns."""
    tof = 1.3 * minimum_multirev_time_s(_MULTIREV_R1, _MULTIREV_R2, MU, revolutions=1)
    direct, _ = solve_lambert(_MULTIREV_R1, _MULTIREV_R2, tof, MU, revolutions=0)
    looping, _ = solve_lambert(_MULTIREV_R1, _MULTIREV_R2, tof, MU, revolutions=1)
    assert float(np.linalg.norm(direct - looping)) > 1.0e2


@pytest.mark.unit
def test_the_two_branches_coalesce_at_the_minimum_time():
    """Limiting case: at the minimum time the two roots merge into one.

    This is what makes the minimum a minimum rather than an arbitrary split point, and it is
    the boundary the infeasibility check is built on.
    """
    tof_min = minimum_multirev_time_s(_MULTIREV_R1, _MULTIREV_R2, MU, revolutions=1)
    tof = tof_min * (1.0 + 1.0e-9)
    v_low, _ = solve_lambert(_MULTIREV_R1, _MULTIREV_R2, tof, MU, revolutions=1, branch="low")
    v_high, _ = solve_lambert(_MULTIREV_R1, _MULTIREV_R2, tof, MU, revolutions=1, branch="high")
    # A metre per second apart out of ~7 km/s: the same arc to five significant figures.
    assert float(np.linalg.norm(v_low - v_high)) < 1.0


@pytest.mark.unit
def test_the_minimum_time_grows_with_the_revolution_count():
    """More laps cannot take less time; a trivially true statement the code must respect."""
    times = [
        minimum_multirev_time_s(_MULTIREV_R1, _MULTIREV_R2, MU, revolutions=n) for n in (1, 2, 3, 4)
    ]
    assert all(times[i] < times[i + 1] for i in range(len(times) - 1)), times


@pytest.mark.unit
def test_time_of_flight_below_the_multi_revolution_minimum_raises():
    tof_min = minimum_multirev_time_s(_MULTIREV_R1, _MULTIREV_R2, MU, revolutions=2)
    with pytest.raises(InfeasibleTransferError, match="no 2-revolution transfer exists"):
        solve_lambert(_MULTIREV_R1, _MULTIREV_R2, 0.9 * tof_min, MU, revolutions=2)


@pytest.mark.unit
def test_the_infeasibility_message_reports_the_minimum_time_it_missed():
    tof_min = minimum_multirev_time_s(_MULTIREV_R1, _MULTIREV_R2, MU, revolutions=1)
    with pytest.raises(InfeasibleTransferError) as excinfo:
        solve_lambert(_MULTIREV_R1, _MULTIREV_R2, 0.5 * tof_min, MU, revolutions=1)
    assert f"{tof_min:.6g}" in str(excinfo.value)


@pytest.mark.unit
def test_minimum_time_query_rejects_zero_revolutions():
    with pytest.raises(ValueError, match="revolutions must be >= 1"):
        minimum_multirev_time_s(_MULTIREV_R1, _MULTIREV_R2, MU, revolutions=0)


# --------------------------------------------------------------------------------------
# Degenerate geometry
# --------------------------------------------------------------------------------------


@pytest.mark.unit
def test_antiparallel_positions_raise_because_the_plane_is_undefined():
    with pytest.raises(DegenerateGeometryError, match="antiparallel"):
        solve_lambert([A_LEO_M, 0.0, 0.0], [-A_LEO_M, 0.0, 0.0], 1000.0, MU)


@pytest.mark.unit
@pytest.mark.parametrize(
    "r2",
    [
        [A_LEO_M, 0.0, 0.0],  # transfer angle 0
        [2.0 * A_LEO_M, 0.0, 0.0],  # transfer angle 0 at a different radius
    ],
)
def test_parallel_positions_raise_because_no_arc_is_swept(r2):
    with pytest.raises(DegenerateGeometryError, match="parallel"):
        solve_lambert([A_LEO_M, 0.0, 0.0], r2, 1000.0, MU)


@pytest.mark.unit
def test_the_degeneracy_message_reports_the_measured_sine():
    with pytest.raises(DegenerateGeometryError, match=r"\|r1 x r2\| / \(\|r1\| \|r2\|\)"):
        solve_lambert([A_LEO_M, 0.0, 0.0], [-A_LEO_M, 0.0, 0.0], 1000.0, MU)


@pytest.mark.unit
@pytest.mark.parametrize(
    ("r1", "r2"),
    [
        ([0.0, 0.0, 0.0], [A_LEO_M, 0.0, 0.0]),
        ([A_LEO_M, 0.0, 0.0], [0.0, 0.0, 0.0]),
        ([0.5, 0.0, 0.0], [0.0, A_LEO_M, 0.0]),
    ],
)
def test_positions_at_the_focus_raise(r1, r2):
    with pytest.raises(DegenerateGeometryError, match="clear of the central body"):
        solve_lambert(r1, r2, 1000.0, MU)


@pytest.mark.unit
def test_a_polar_transfer_plane_raises_because_prograde_is_undefined():
    """``h_z = 0`` is where the direction convention has nothing to read."""
    with pytest.raises(DegenerateGeometryError, match="polar transfer"):
        solve_lambert([A_LEO_M, 0.0, 0.0], [0.0, 0.0, A_LEO_M], 1000.0, MU)


@pytest.mark.unit
def test_a_transfer_just_off_polar_is_accepted_and_picks_a_definite_direction():
    """Complement to the polar guard: it must be a knife edge, not a wide exclusion zone.

    One part in 1e6 off the z axis is enough for ``h_z`` to have a meaningful sign, and the
    solver takes it. If this raised too, the guard would be rejecting ordinary
    high-inclination transfers rather than the single undefined case.
    """
    r2 = np.array([0.0, 1.0e-6 * A_LEO_M, A_LEO_M])
    v1, _ = solve_lambert([A_LEO_M, 0.0, 0.0], r2, 0.25 * PERIOD_S, MU)
    assert float(np.cross(np.array([A_LEO_M, 0.0, 0.0]), v1)[2]) > 0.0


@pytest.mark.unit
def test_the_transfer_plane_becomes_ill_conditioned_near_180_degrees():
    """Complement test for the antiparallel guard: the degeneracy is real, not conservative.

    The guard rejects the exactly-collinear case. This shows *why*, and that the guard is
    sitting on a genuine cliff rather than an arbitrary line: displacing the arrival point by
    one metre out of plane -- on a vector of 2.6e7 m -- swings the resulting orbit normal by
    9e-6 degrees at a 150-degree transfer and by 2.5 degrees at 179.9999 degrees, a
    sensitivity amplification of about 280000.

    It also records a limitation honestly: the default ``collinear_tol`` of 1e-8 on
    ``|sin(dtheta)|`` guards *definedness*, not accuracy. Answers returned between roughly
    179.999 degrees and the guard are progressively ill-conditioned, and a caller who needs a
    trustworthy plane there should tighten ``collinear_tol`` themselves.
    """
    r_inner = R_EARTH_EQUATORIAL_M + 400.0e3
    r_outer = R_EARTH_EQUATORIAL_M + 20000.0e3
    tof = math.pi * math.sqrt((0.5 * (r_inner + r_outer)) ** 3 / MU)
    r1 = np.array([r_inner, 0.0, 0.0])

    swings = []
    for degrees in (150.0, 179.9999):
        angle = math.radians(degrees)
        base = r_outer * np.array([math.cos(angle), math.sin(angle), 0.0])
        normals = []
        for offset in (-1.0, 1.0):
            v1, _ = solve_lambert(r1, base + np.array([0.0, 0.0, offset]), tof, MU)
            h = np.cross(r1, v1)
            normals.append(h / np.linalg.norm(h))
        cosine = min(1.0, max(-1.0, float(np.dot(normals[0], normals[1]))))
        swings.append(math.degrees(math.acos(cosine)))

    assert swings[0] < 1e-3, f"a 150-degree transfer should be well conditioned: {swings[0]}"
    assert swings[1] > 1.0, (
        f"the near-180-degree plane should be violently sensitive, but a 1 m perturbation "
        f"moved the orbit normal by only {swings[1]:.3e} degrees"
    )


# --------------------------------------------------------------------------------------
# Convergence failure
# --------------------------------------------------------------------------------------


@pytest.mark.unit
def test_running_out_of_iterations_raises_instead_of_returning_the_last_iterate():
    with pytest.raises(LambertConvergenceError, match="did not converge"):
        solve_lambert(R1_LEO, R2_LEO_QUARTER, 0.25 * PERIOD_S, MU, max_iterations=1)


@pytest.mark.unit
def test_the_convergence_error_carries_the_numbers_needed_to_act_on_it():
    with pytest.raises(LambertConvergenceError) as excinfo:
        solve_lambert(R1_LEO, R2_LEO_QUARTER, 0.25 * PERIOD_S, MU, max_iterations=2)
    error = excinfo.value
    assert error.iterations == 2
    assert math.isfinite(error.residual_s) and abs(error.residual_s) > 0.0
    assert error.tof_s == pytest.approx(0.25 * PERIOD_S)


@pytest.mark.unit
def test_a_tolerance_below_the_arithmetic_noise_floor_raises_rather_than_pretending():
    """Asking for a residual the double-precision time equation cannot resolve must fail.

    This is a different refusal path from running out of iterations: here the bracket has
    collapsed onto adjacent floats and the answer is as good as double precision allows, but
    it still does not meet what was asked for. Reporting that is the whole contract.

    The case matters. For an exactly circular quarter orbit the root is representable and the
    residual comes out at exactly zero, so *any* tolerance is met -- correctly. The 28.8-degree
    circular arc used here has a root that is not exactly representable, and 15 of the 20
    cases in ``_PROPAGATION_CASES`` behave the same way at 1e-16 and below.

    The refused answer is checked to be numerically excellent regardless: the point is that
    "very close" is reported as a failure to meet the stated tolerance rather than passed off
    as success.
    """
    r1, r2, tof, _ = _endpoints(0.0, 0.08)
    with pytest.raises(LambertConvergenceError, match="residual") as excinfo:
        solve_lambert(r1, r2, tof, MU, time_rtol=1e-18)
    assert abs(excinfo.value.residual_s) > 1e-18 * tof
    assert abs(excinfo.value.residual_s) < 1e-9, (
        "the refused iterate should be numerically excellent -- the refusal is about the "
        "requested tolerance being unreachable, not about the answer being bad"
    )


@pytest.mark.unit
def test_an_unbracketable_time_of_flight_raises():
    """A quarter turn in a microsecond is outside what the time equation can bracket."""
    with pytest.raises(LambertConvergenceError, match="could not bracket"):
        solve_lambert(R1_LEO, R2_LEO_QUARTER, 1.0e-6, MU)


@pytest.mark.unit
def test_the_root_solve_converges_inside_a_measured_iteration_budget():
    """Pin the *cost* of convergence, not just the fact of it.

    ``max_iterations`` is the only handle the public API gives on how hard the solver worked,
    and running the whole sweep against a tight cap turns it into an assertion: if the
    iteration count regresses, this raises.

    That matters because the root solve can degrade silently. The Illinois modification of
    regula falsi must halve the retained endpoint's function value only when the *same*
    endpoint is retained twice running; applying it on every step instead corrupts both
    stored values symmetrically and collapses the method to plain bisection. Everything still
    converges to the same answer, every accuracy test in this file still passes, and the cost
    goes from 4-13 iterations to 30-41. Nothing else here would notice.

    Measured: 7 to 9 iterations for the single-revolution sweep and 8 to 13 for the
    multi-revolution branches. A cap of 20 is comfortable headroom over 13 while sitting well
    below the 30 that the degraded iteration needs.
    """
    for eccentricity, fraction in _PROPAGATION_CASES:
        r1, r2, tof, _ = _endpoints(eccentricity, fraction)
        solve_lambert(r1, r2, tof, MU, max_iterations=20)

    for revolutions in (1, 2, 3):
        tof_min = minimum_multirev_time_s(_MULTIREV_R1, _MULTIREV_R2, MU, revolutions=revolutions)
        for factor in (1.05, 1.5, 2.5):
            for branch in ("low", "high"):
                solve_lambert(
                    _MULTIREV_R1,
                    _MULTIREV_R2,
                    factor * tof_min,
                    MU,
                    revolutions=revolutions,
                    branch=branch,
                    max_iterations=20,
                )


# --------------------------------------------------------------------------------------
# Input validation
# --------------------------------------------------------------------------------------


@pytest.mark.unit
@pytest.mark.parametrize("bad_tof", [0.0, -1.0, -PERIOD_S, float("nan"), float("inf")])
def test_non_positive_or_non_finite_time_of_flight_raises(bad_tof):
    with pytest.raises(ValueError, match="tof_s"):
        solve_lambert(R1_LEO, R2_LEO_QUARTER, bad_tof, MU)


@pytest.mark.unit
@pytest.mark.parametrize("bad_mu", [0.0, -1.0, float("nan")])
def test_non_positive_gravitational_parameter_raises(bad_mu):
    with pytest.raises(ValueError, match="mu_m3_s2"):
        solve_lambert(R1_LEO, R2_LEO_QUARTER, 1000.0, bad_mu)


@pytest.mark.unit
@pytest.mark.parametrize("bad_shape", [np.zeros(2), np.zeros(4), np.zeros((3, 1))])
def test_wrong_position_shape_raises(bad_shape):
    with pytest.raises(ValueError, match="shape"):
        solve_lambert(bad_shape, R2_LEO_QUARTER, 1000.0, MU)


@pytest.mark.unit
@pytest.mark.parametrize("bad_value", [np.nan, np.inf])
def test_non_finite_position_raises(bad_value):
    with pytest.raises(ValueError, match="finite"):
        solve_lambert([A_LEO_M, 0.0, bad_value], R2_LEO_QUARTER, 1000.0, MU)
    with pytest.raises(ValueError, match="finite"):
        solve_lambert(R1_LEO, [A_LEO_M, bad_value, 0.0], 1000.0, MU)


@pytest.mark.unit
def test_negative_revolutions_raises():
    with pytest.raises(ValueError, match="revolutions must be >= 0"):
        solve_lambert(R1_LEO, R2_LEO_QUARTER, 1000.0, MU, revolutions=-1)


@pytest.mark.unit
@pytest.mark.parametrize("bad_revolutions", [1.5, True, "1", None])
def test_non_integer_revolutions_raises(bad_revolutions):
    """``True`` is included deliberately: ``bool`` is an ``int`` subclass in Python.

    Without the explicit rejection, ``revolutions=True`` would silently mean "one
    revolution", which is a plausible typo for ``prograde=True`` in the wrong slot.
    """
    with pytest.raises(ValueError, match="revolutions must be an integer"):
        solve_lambert(R1_LEO, R2_LEO_QUARTER, 1000.0, MU, revolutions=bad_revolutions)


@pytest.mark.unit
def test_numpy_integer_revolutions_are_accepted():
    """Complement to the type check: it must reject wrong types, not all non-``int`` types."""
    tof = 1.3 * minimum_multirev_time_s(_MULTIREV_R1, _MULTIREV_R2, MU, revolutions=1)
    from_python = solve_lambert(_MULTIREV_R1, _MULTIREV_R2, tof, MU, revolutions=1)[0]
    from_numpy = solve_lambert(_MULTIREV_R1, _MULTIREV_R2, tof, MU, revolutions=np.int64(1))[0]
    np.testing.assert_array_equal(from_python, from_numpy)


@pytest.mark.unit
@pytest.mark.parametrize("bad_branch", ["mid", "LOW", "", None])
def test_unrecognised_branch_raises(bad_branch):
    with pytest.raises(ValueError, match="branch must be"):
        solve_lambert(R1_LEO, R2_LEO_QUARTER, 1000.0, MU, revolutions=1, branch=bad_branch)


@pytest.mark.unit
@pytest.mark.parametrize("bad_iterations", [0, -5])
def test_non_positive_iteration_cap_raises(bad_iterations):
    with pytest.raises(ValueError, match="max_iterations"):
        solve_lambert(R1_LEO, R2_LEO_QUARTER, 1000.0, MU, max_iterations=bad_iterations)


@pytest.mark.unit
@pytest.mark.parametrize("bad_rtol", [0.0, -1e-12])
def test_non_positive_time_tolerance_raises(bad_rtol):
    with pytest.raises(ValueError, match="time_rtol"):
        solve_lambert(R1_LEO, R2_LEO_QUARTER, 1000.0, MU, time_rtol=bad_rtol)


@pytest.mark.unit
def test_non_positive_minimum_radius_raises():
    with pytest.raises(ValueError, match="min_radius_m"):
        solve_lambert(R1_LEO, R2_LEO_QUARTER, 1000.0, MU, min_radius_m=0.0)


@pytest.mark.unit
def test_the_gravitational_parameter_defaults_to_earth():
    explicit = solve_lambert(R1_LEO, R2_LEO_QUARTER, 0.25 * PERIOD_S, MU_EARTH_M3_S2)[0]
    implied = solve_lambert(R1_LEO, R2_LEO_QUARTER, 0.25 * PERIOD_S)[0]
    np.testing.assert_array_equal(explicit, implied)


@pytest.mark.unit
def test_the_solver_works_for_a_non_earth_central_body():
    """Nothing in the module may assume Earth; the only scale is ``mu``.

    Scaling ``mu`` by k and lengths by 1 scales times by 1/sqrt(k), so solving the scaled
    problem at the scaled time must give velocities scaled by sqrt(k). Checked against the
    Sun's gravitational parameter to make the scale ratio large.
    """
    mu_sun = 1.32712440018e20
    ratio = mu_sun / MU
    tof = 0.25 * PERIOD_S / math.sqrt(ratio)
    v_earth, _ = solve_lambert(R1_LEO, R2_LEO_QUARTER, 0.25 * PERIOD_S, MU)
    v_sun, _ = solve_lambert(R1_LEO, R2_LEO_QUARTER, tof, mu_sun)
    # atol is needed because the radial component of a circular arc is a numerical zero
    # (~1e-9 m/s against a 4.4e6 m/s speed); comparing that relatively compares noise.
    np.testing.assert_allclose(v_sun, v_earth * math.sqrt(ratio), rtol=1e-10, atol=1e-6)
